# 1. add SERVICE_ACCOUNT_KEY secret
#    https://docs.github.com/ru/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions


name: Build and Push to Artifact Registry

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  # Set your value
  PROJECT_ID: neon-fiber-432820-v5
  # Set your value
  GAR_LOCATION: us-east1
  # Set your value
  REPOSITORY: neon-fiber-test
  # Set your value
  IMAGE: main

jobs:
  build-push-artifact:
    environment: "test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet

      - name: Check for Artifact Repository
        id: check-repo
        run: |
            if gcloud artifacts repositories list --format="value(name)" | grep -q ${{ env.REPOSITORY }}; then
              echo "Repository ${{ env.REPOSITORY }} exists."
            else
              echo "Repository ${{ env.REPOSITORY }} does not exist. Creating it now..."
              gcloud artifacts repositories create ${{ env.REPOSITORY }} --repository-format=docker --location=${{env.GAR_LOCATION}} --description="Docker repository"
            fi

      - name: Build image
        run: |-
          docker build --tag "${{env.GAR_LOCATION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPOSITORY}}/${{env.IMAGE}}:${{ github.sha }}" .

      - name: Push image
        run: |-
          docker push "${{env.GAR_LOCATION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPOSITORY}}/${{env.IMAGE}}:${{ github.sha }}"
